version: '3.5'

services:
  postgres:
    image: postgres:15-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${TYPE_ORM_USERNAME}
      POSTGRES_PASSWORD: ${TYPE_ORM_PASSWORD}
      POSTGRES_DB: ${TYPE_ORM_DATABASE}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - ${TYPE_ORM_PORT}:5432

volumes:
    postgres: